sonar.projectKey=ParidhiJuneja_devsecops-demo
sonar.organization=paridhijuneja
sonar.projectName=devsecops-demo
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.13
sonar.sourceEncoding=UTF-8